FROM node:18.20.8-bookworm-slim

WORKDIR /workspace
COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

COPY . ./

EXPOSE 4200
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
