
#test config
# prod for Munich side server
# PostgresSQL Configuration 146.107.176.173, 172.17.15.209
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/starTrack
spring.datasource.username=postgres
spring.datasource.password=${STARTRACK_DB_PASSWORD}
server.port=443
app.oauth2.authorizedRedirectUris=https://srvphstrata.srv.med.uni-muenchen.de:443/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect
client.url=https://srvphstrata.srv.med.uni-muenchen.de:443

